### ISSUE TITLE
inactive Traits

### ISSUE THREAD

**Issue by biodiv** [localcosmos/app-kit#9]
add the ability to set traits to "inactive", like identification tree nodes.

**Comment by Meinolf-geoGLIS** [comment]
So sieht es sonst ohne ausgewählte Merkmale schon aus, ich kann bestimmte unnütze Merkmale nicht auswählen:
![image](https://github.com/localcosmos/app-kit/assets/58850976/9f49a194-784a-4b60-a08f-c3e05f8837de)

**Comment by biodiv** [comment]
enthalten seit dem heutigen Update
